### PR TITLE
v2.0

### PR DESCRIPTION
**Pull request by jeemok**
You can install it by `npm install better-npm-audit@next`

* [Readme](https://github.com/jeemok/better-npm-audit/blob/next/README.md)
* [Changelog](https://github.com/jeemok/better-npm-audit/blob/next/CHANGELOG.md)

### Notable changes

* Simplified the workflow and improved overall performance by running lesser in the process.
* Added [`table`](https://www.npmjs.com/package/table) module to display summaries (Initially used [`cli-table`](https://www.npmjs.com/package/cli-table) for its small size, however the issues in the repo concerns me in its display quality in other OS. Hence, chosen `table` module despite its package size is much bigger)
* Added table display for security report
* Added table display of exceptions from `.nsprc` file
* Cleaned up test cases structure to be more straight forward and easier to maintain

### Breaking changes

* Renamed `--ignore -i` flag to `--exclude -x` for better clarity.
* Removed `--display-full` flag that was used to ignore the maximum display limit. Now with the summary table it would be unlikely to display large size of information.
* Removed `--display-notes` flag that was used for displaying exception notes. Now it is included in the exceptions table.
* Renamed `ignore` field to `active` in `.nsprc` file for better clarity.
* Renamed `reason` field to `notes` in `.nsprc` file for better clarity.

### Others

* Removed logging of flags used in the command
* Added NPM audit into the CI pipeline
* Added `.github/FUNDING.yml`
* Updated `README.md`

## Closed issues

* [#20](https://github.com/jeemok/better-npm-audit/issues/20) Provide more output when parsing exceptions file
* [#27](https://github.com/jeemok/better-npm-audit/issues/27) Hide excepted vulnerabilities from output
* [#28](https://github.com/jeemok/better-npm-audit/issues/28) Missing [ in truncation message

### CODE REVIEW

**Comment by jeemok** [comment]
Trading size for quality...

Screen Shot 2021-06-21 at 11 22 24 AM

**Comment by jeemok** [comment]
Hey @alertme-edwin, I'm happy to present this next version to you that takes the suggestions you given in the past and made a few improvements too! Feel free to test this out and let me know what you think!

**Comment by alertme-edwin** [comment]
I've just been trying out version `2.0.3-rc` and the experience is fantastic!  This is great work, thank you!

The output is now really succinct and readable, which should help new users to instantly see the benefit of this tool.

If I can just offer a small correction, the string:

`1 vulnerabilities where excluded but did not result in a vulnerabilities: XXX. They can be removed...`

would perhaps be better if worded like this instead:

`1 of the excluded vulnerabilities did not match any of the found vulnerabilities: XXX. It can be removed...`

with "They can" being used if there is more than one.

**Comment by jeemok** [comment]
@alertme-edwin Glad to hear that! Thanks for the wording suggestion, let me add it in now 👍🏻

**Pull request merged**
